### ISSUE TITLE
Fluent error

### ISSUE THREAD

**Issue by pr-acassera** [Juniper/open-nti#171]
I just installed opennti and I am getting the following error from the logs 

docker logs opennti_input_jti

error=#<Protobuf::InvalidWireType: 7> error_class=Protobuf::InvalidWireType host="10.150.0.5"

This keeps repeating over and over again.

My install is on Ubuntu 16.04 server

Config on switch is the following:

PixelAdmin@prtgc-qfx5100-vc-1# show services
analytics {
    export-profiles {
        default-export_file {
            stream-format gpb;
            interface {
                information;
                statistics {
                    traffic;
                    queue;
                }
                status {
                    link;
                }
            }
            system {
                information;
                status {
                    traffic;
                    queue;
                }
            }
        }
    }
    resource-profiles {
        sys-rp {
            queue-monitoring;
            traffic-monitoring;
            depth-threshold high 99999 low 99;
        }
        if-rp {
            queue-monitoring;
            traffic-monitoring;
            latency-threshold high 2300 low 20;
        }
    }
    resource {
        system {
            resource-profile sys-rp;
            polling-interval {
                traffic-monitoring 5;
                queue-monitoring 1000;
            }
        }
        interfaces {
            ge-1/0/0 {
                resource-profile if-rp;
            }
            xe-1/0/46 {
                resource-profile if-rp;
            }
        }
    }
    collector {
        address 10.0.12.129 {
            port 50000 {
                transport udp {
                    export-profile default-export_file;
                }
            }
        }
    }
}

I also am not getting any data populated in dashboard.

More errors below:

2017-06-22 15:50:00 -0400 fluent.error: {"error":"#<Protobuf::InvalidWireType: 3>","error_class":"Protobuf::InvalidWireType","host":"10.150.0.5","message":"\"\\xD3\\b\\x00\\x00\\x01\\x00\\x00\\x00\\b\\xB1\\xE5\\xE9\\xD1\\x9C\\xD2\\xD4\\x02\\x1Ab\\n\\x1Cprtgc-qfx5100-vc-1:ge-1/0/17\\\"B\\n@\\x10\\x84\\xBC\\xCC\\xD5\\x01\\x18\\x96\\xE1\\x9E\\xD5\\x01 #(\\xCB\\xDA-0\\f8\\x81\\xD6\\x82\\xEF\\xE7\\a@\\xB0\\x0EX\\x8D\\x8D\\xCD\\xCD\\x01`\\xEC\\xFC\\xAF\\xCA\\x01h\\xDE\\xD7\\x9C\\x03p\\xC38x\\x0E\\x80\\x01\\x9E\\x98\\x9E\\xC5\\x8E\\x04\\x88\\x01\\xFE\\x0E\\x1AW\\n\\x1Cprtgc-qfx5100-vc-1:ge-1/0/21\\\"7\\n5\\x10\\xD9\\xF9\\xEA\\n\\x18\\x9A\\x99\\xC1\\n ,(\\x93\\xE0)8\\xFA\\x82\\xE5\\xFB\\x05@ X\\x99\\xFB\\x8D\\x0E`\\xBD\\xE4\\xC3\\nh\\xCC\\xD7\\x9C\\x03p\\x90\\xBF-\\x80\\x01\\x8C\\x8E\\xA7\\xC0\\t\\x88\\x01 \\x1Aw\\n\\x1Eprtgc-qfx5100-vc-1:xe-1/0/50:0\\\"U\\nS\\x10\\xEB\\xF7\\xB2\\x9D\\xDF\\x01\\x18\\xDF\\xCF\\xE1\\x9B\\xDF\\x01 \\xD2\\x04(\\xBA\\xA3\\xD1\\x010\\xB7\\x128\\x9E\\x89\\xCB\\xB4\\x8A\\xF6<@\\xBE\\xC5!X\\x87\\x8C\\xA5\\xF2\\xCE\\x01`\\x8B\\x96\\x8B\\xC5\\xCE\\x01h\\xB2\\xF4\\xE7\\rp\\xCA\\x81\\xB2\\x1Fx\\xCF#\\x80\\x01\\xAB\\x83\\xAB\\x85\\xF0\\xC1@\\x88\\x01\\xC4\\xF2\\xA7\\x10\\x98\\x01\\xF4\\x01\\x1Ar\\n\\x1Eprtgc-qfx5100-vc-1:xe-1/0/50:1\\\"P\\nN\\x10\\x8D\\xB6\\xB2\\xF9\\xF3\\x01\\x18\\xD4\\xAA\\xB1\\xF8\\xF3\\x01 \\x99\\x03(\\xA0\\x88\\x81\\x018\\xCE\\xD4\\xC3\\x82\\xBE\\x9A5H\\x82\\x83\\x02X\\x88\\xA2\\x88\\xCD\\xD8\\x01`\\xBD\\xF7\\xAB\\x9F\\xD8\\x01h\\xC3\\xF4\\xE7\\rp\\x88\\xB6\\xF4\\x1Fx\\x02\\x80\\x01\\xE3\\xF6\\x9B\\xC9\\xF4\\xE71\\x88\\x01\\x98\\x01\\x98\\x01\\x88\\x89\\x02\\x1Ap\\n\\x1Eprtgc-qfx5100-vc-1:xe-1/0/50:2\\\"N\\nL\\x10\\xFC\\xF9\\xA5\\xB8s\\x18\\xA7\\xB8\\xD6\\xB7s \\xF5C(\\xE0\\xFDN0\\xAD\\x018\\xAB\\xD0\\xA8\\xFC\\x93\\xF6\\#@\\x81\\xE6;X\\xBF\\xD0\\x90\\xC4z`\\xC8\\xA3\\x91\\x96zh\\xFB\\xAC\\xE7\\rp\\xFC\\xFF\\x97 x\\x97\\x01\\x80\\x01\\xA1\\xCF\\x96\\xFF\\xB4\\xB0#\\x88\\x01\\xFE\\x88\\x15\\x98\\x01\\t\\x1Ac\\n\\x1Eprtgc-qfx5100-vc-1:xe-1/0/50:3\\\"A\\n?\\x10\\xCF\\x89\\xC1>\\x18\\xA1\\xB3\\x8A> \\x94\\x88!(\\x9A\\xCE\\x158\\x9A\\xA5\\xE3\\x80\\xA0\\x17X\\x95\\xBE\\x9FX`\\x99\\x90\\xF7=h\\x88\\xA6\\xBF\\bp\\xF4\\x87\\xE9\\x11x\\x02\\x80\\x01\\x95\\xCB\\xE9\\xC3\\xCD\\x15\\x88\\x01\\x98\\x01\\x98\\x01\\x89\\x01\\x1Ak\\n\\x1Eprtgc-qfx5100-vc-1:xe-1/0/51:0\\\"I\\nG\\x10\\xAF\\x9E\\xF8\\xCB8\\x18\\x83\\x9D\\xF6\\xCB8(\\xAC\\x81\\x020\\xD3\\a8\\xB6\\xBB\\x82\\xD5\\xAE\\x82\\x13@\\xC1\\xE2\\x9E\\x03X\\xD9\\x9D\\x9A\\x8D9`\\xA4\\xAB\\xCD\\xDE8h\\x8B\\xF6\\xE7\\rp\\xAA\\xFC\\xE4 x\\x93\\x05\\x80\\x01\\xD4\\xEC\\xE3\\xD0\\xFE\\xEA\\r\\x88\\x01\\xA4\\xE3\\x04\\x1AL\\n\\x1Eprtgc-qfx5100-vc-1:xe-1/0/51:1\\\"*\\n(\\x10\\x02(\\x028\\x88\\x01X\\xD0\\xB6\\x861`\\xDF\\xC2\\xB7\\x02h\\xA7\\xF6\\xE7\\rp\\xCA\\xFD\\xE6 x\\x02\\x80\\x01\\xCC\\xFF\\xFF\\xADF\\x88\\x01\\x98\\x01\\x1A]\\n\\x1Eprtgc-qfx5100-vc-1:xe-1/0/51:2\\\";\\n9\\x10\\xFD\\x87\\x9D/\\x18\\xC1\\x87\\x9D/(<8\\xFD\\x9E\\x8F\\xA6\\x9C\\x10X\\x8B\\xE9\\xA6c`\\xAB\\xF6\\xD74h\\xCD\\xF5\\xE7\\rp\\x93\\xFD\\xE6 x\\x02\\x80\\x01\\xAF\\x93\\xE4\\xCD\\xFD\\x13\\x88\\x01\\x98\\x01\\x98\\x01\\xAB\\x05\\x1Ak\\n\\x1Eprtgc-qfx5100-vc-1:xe-1/0/51:3\\\"I\\nG\\x10\\xD5\\xA3\\xEB\\xC6R\\x18\\x95\\xC4\\xE7\\xC6R(\\xC0\\xDF\\x030\\xE3\\n8\\xA8\\xF2\\x9B\\xCA\\xEB\\x9A\\e@\\x8D\\xF2\\x98\\x05X\\xD0\\xA7\\x9B\\xB9U`\\xBF\\x93\\xD0\\x8AUh\\xFC\\xF5\\xE7\\rp\\x95\\x9E\\xE3 x\\x93\\x04\\x80\\x01\\xB3\\xE1\\xD9\\xFB\\x91\\xF6\\x17\\x88\\x01\\x97\\xBA\\x03\\x1Ad\\n\\eprtgc-qfx5100-vc-1:xe-1/0/1\\\"E\\nC\\x10\\xEC\\xEF\\xE4\\x95\\x01\\x18\\x9A\\x91\\xED\\x83\\x01 \\xA6\\x9D\\xE7\\f(\\xAC\\xC1\\x90\\x058\\xAC\\xB6\\x95\\xF5\\xE1\\x01@ X\\xBF\\xBC\\xBA\\x97\\x02`\\xCF\\xFB\\xC6\\x80\\x01h\\xD0\\xE8\\xA39p\\xA0\\xD8\\xCF]x\\t\\x80\\x01\\xA9\\xA5\\xAE\\xEF\\xE0\\x02\\x88\\x01\\xC8\\x16\\x1AC\\n\\eprtgc-qfx5100-vc-1:ge-1/0/0\\\"$\\n\\\"X\\xF1\\xBC\\xB6\\xC1\\x01`\\x9D\\x93^h\\xA8\\xEE\\xD28p\\xAC\\xBB\\x85\\x88\\x01x\\t\\x80\\x01\\x8A\\xBE\\xA4\\x99}\\x88\\x01\\x89\\x06\\x1Aa\\n\\x1Cprtgc-qfx5100-vc-1:ge-1/0/32\\\"A\\n?\\x10\\xDC\\x8E\\xBC&\\x18\\xA5\\xFA\\x98& \\xD5\\xD6\\b(\\xE2\\xBD\\x1A8\\xB7\\xEB\\xED\\xD0\\xB3\\x01X\\xC5\\xCA\\xDBI`\\xF0\\xDA\\xBC3h\\x92\\x8E\\x9C\\ap\\xC3\\xE1\\x82\\x0Fx\\x02\\x80\\x01\\x94\\xC1\\xC0\\xE8\\xD9\\x02\\x88\\x01\\x90\\x01\\x98\\x01\\xA9=\\x1Ad\\n\\x1Eprtgc-qfx5100-vc-1:xe-1/0/53:0\\\"B\\n@\\x10\\xF9\\x9A\\xC0\\x93\\x16\\x18\\xAE\\x9E\\xE9\\x92\\x16 \\x88\\x03(\\xC3\\xF9V8\\xD2\\xF5\\xF0\\xB9\\x97\\xD3\\x04X\\xDD\\xF0\\x8C\\xE5\\x1C`\\xDE\\xB5\\xB6\\xC2\\x1Ch\\xB4\\x9C\\xC8\\np\\xCB\\x9E\\x8E\\x18x\\x02\\x80\\x01\\xC7\\xA2\\x93\\x9A\\x96\\xCD\\n\\x88\\x01\\x98\\x01\\x1Ac\\n\\x1Eprtgc-qfx5100-vc-1:xe-1/0/53:1\\\"A\\n?\\x10\\xAB\\xF9\\x99\\xB9\\x03\\x18\\xD3\\xD7\\xEF\\xB8\\x03 \\x81\\x02(\\xD7\\x9F*8\\xBA\\xBA\\xAA\\x93\\xFANX\\xE2\\xB4\\xD5\\xC2\\x05`\\xF1\\xD9\\xDF\\x9F\\x05h\\x91\\x9D\\xC8\\np\\xE0\\xBD\\xAD\\x18x\\x02\\x80\\x01\\xE5\\xC4\\xC9\\xC3\\xED\\xF9\\x01\\x88\\x01\\x98\\x01\\x1A|\\n\\x1Cprtgc-qfx5100-vc-1:xe-1/0/46\\\"\\\\\\nZ\\x10\\xB0\\xA4\\xC4\\x87\\xB2\\x11\\x18\\xDE\\xAF\\xA2\\xE7\\xB1\\x11 \\xC8\\xF0\\x98\\x18(\\x8A\\x84\\x89\\b0\\x8B\\x91\\x038\\xF2\\xE1\\xA1\\xC2\\xF4\\xB5\\xC5\\x01@\\xBC\\xCD\\xF2#H\\x04X\\xD4\\xC4\\xC4\\xDA\\x80\\x03`\\xFC\\xE4\\xCA\\xFE\\xFF\\x02h\\xC3\\xF3\\xC0\\x1Ap\\x95\\xEC\\xB8Ax\\xF9:\\x80\\x01\\x9B\\xD2\\xD0\\xB1\\xDE\\x8F\\x13\\x88\\x01\\x89\\x8D\\x90\\x01\\x98\\x01\\x9B\\x01\\x1Aj\\n\\eprtgc-qfx5100-vc-1:ge-1/0/3\\\"K\\nI\\x10\\xE2\\x8A\\xBF\\x8AM\\x18\\x87\\xA2\\x92\\x88M \\x8E\\xF6\\xAB\\x02(\\xCDr0\\x8A\\x168\\xD1\\xA2\\x85\\x9D\\xEA\\xEC\\x03@\\xC4\\xBBVX\\xAC\\xE1\\xA9\\xF1D`\\xA7\\xF8\\xC3\\xEEDh\\xC4\\x8A\\xE5\\x02p\\xC1^x\\xDC,\\x80\\x01\\xEF\\xB9\\xD2\\x9B\\xA5\\xCB\\x03\\x88\\x01\\xF4\\x9B\\xCD\\x03\\x1Ak\\n\\x1Eprtgc-qfx5100-vc-1:xe-1/0/52:0\\\"I\\nG\\x10\\xBC\\xD8\\xA5\\xEE\\x02\\x18\\xB8\\x8C\\x8F\\xEE\\x02 L(\\xB8\\xCB\\x160\\x95\\x018\\xAB\\xF1\\xD4\\x98\\xE3;@\\xDF\\xFC\\x04X\\x8E\\x8F\\xB1\\xF4\\x03`\\xDA\\x9A\\x88\\xF2\\x03h\\x84\\x95kp\\xB0\\xDF\\xBD\\x01x\\xAA\\x02\\x80\\x01\\x9A\\xFA\\xA8\\xC1\\xE9\\xB7\\x01\\x88\\x01\\x80\\xF2\\x88\\x01\\x1Ak\\n\\x1Eprtgc-qfx5100-vc-1:xe-1/0/52:1\\\"I\\nG\\x10\\x95\\xFF\\xD0\\xEA\\x02\\x18\\x89\\x9A\\xC4\\xEA\\x02 L(\\xC0\\xE4\\f0\\xB1\\x018\\xE9\\xF8\\x99\\x82\\xBB;@\\x94\\xAE\\x04X\\xB0\\xD9\\xCF\\xED\\x03`\\x9E\\x80\\x9D\\xEB\\x03h\\xB7\\x94kp\\xDB\\xC4\\xC7\\x01x\\xE6\\x02\\x80\\x01\\xA5\\x83\\x99\\xCA\\xC3\\xB6\\x01\\x88\\x01\\xAA\\xD2\\xA9\\x01\\x1Ai\\n\\x1Eprtgc-qfx5100-vc-1:xe-1/0/52:2\\\"G\\nE\\x10\\xC6\\xED\\x81\\xED\\x06\\x18\\xF1\\xAE\\x81\\xED\\x06(\\xD5>0\\xCD\\t8\\xF8\\xDB\\x8E\\xED\\x94\\xA7\\x02@\\xAB\\xFE\\x9D\\x04X\\x9A\\xFE\\xB0\\xF1\\x06`\\xE1\\xC8\\xF5\\xEE\\x06h\\xFB\\x97kp\\xBE\\x9D\\xD0\\x01x\\xC1\\x06\\x80\\x01\\xE7\\x96\\x95\\xE7\\x85\\xC9\\x01\\x88\\x01\\xC8\\xBA\\x05\\x1Ai\\n\\x1Eprtgc-qfx5100-vc-1:xe-1/0/52:3\\\"G\\nE\\x10\\xFF\\xD2\\xE0\\x9A\\x06\\x18\\xDB\\x94\\xE0\\x9A\\x06(\\xA4>0\\xF0\\t8\\xF0\\x86\\xCE\\x98\\xA9\\x88\\x02@\\x8C\\x9E\\xB8\\x04X\\xF9\\xD3\\xD6\\x93\\x06`\\x90\\x9E\\x9B\\x91\\x06h\\xFD\\x97kp\\xEC\\x9D\\xD0\\x01x\\xD9\\x06\\x80\\x01\\xD1\\xCF\\xB2\\xF6\\xB0\\xBE\\x01\\x88\\x01\\xCE\\xD8\\x05\\x1AM\\n\\x1Cprtgc-qfx5100-vc-1:xe-1/0/36\\\"-\\n+\\x10\\xEC\\xB2\\x9C$\\x18\\xF9\\xAF\\x9C$  (\\xD3\\x028\\x97\\xBD\\xB6\\xC4\\xAD\\x03X\\xBF\\xAFQ`\\xD0\\x84Oh\\xD6\\xAD\\x01p\\x99}\\x80\\x01\\xE3\\xA7\\xC7-\" error=#<Protobuf::InvalidWireType: 3> error_class=Protobuf::InvalidWireType host=\"10.150.0.5\""}
2017-06-22 15:50:00 -0400 [error]: "0\x00\x00\x00\x01\x00\x00\x00\b\xD1\xB8\xEB\xD1\x9C\xD2\xD4\x02\x1A%\n\x1Cprtgc-qfx5100-vc-1:xe-0/0/16\"\x05\x12\x03\x10\xC0\x06" error=#<Protobuf::InvalidWireType: 4> error_class=Protobuf::InvalidWireType host="10.150.0.5"
  2017-06-22 15:50:00 -0400 [error]: suppressed same stacktrace
2017-06-22 15:50:00 -0400 [error]: "2\x00\x00\x00\x01\x00\x00\x00\b\x8C\xA9\xEC\xD1\x9C\xD2\xD4\x02\x1A'\n\x1Eprtgc-qfx5100-vc-1:xe-1/0/50:0\"\x05\x12\x03\x10\xE00" error=#<TypeError: Expected value of type 'Protobuf::Field::Uint64Field' for field timestamp, but got 'String'> error_class=TypeError host="10.150.0.5"
  2017-06-22 15:50:00 -0400 [error]: /usr/lib/ruby/gems/2.3.0/gems/protobuf-3.7.5/lib/protobuf/field/varint_field.rb:69:in `coerce!'
  2017-06-22 15:50:00 -0400 [error]: /usr/lib/ruby/gems/2.3.0/gems/protobuf-3.7.5/lib/protobuf/message.rb:213:in `set_field'
  2017-06-22 15:50:00 -0400 [error]: /usr/lib/ruby/gems/2.3.0/gems/protobuf-3.7.5/lib/protobuf/message.rb:163:in `[]='
  2017-06-22 15:50:00 -0400 [error]: /usr/lib/ruby/gems/2.3.0/gems/protobuf-3.7.5/lib/protobuf/field/base_field.rb:138:in `set'
  2017-06-22 15:50:00 -0400 [error]: /usr/lib/ruby/gems/2.3.0/gems/protobuf-3.7.5/lib/protobuf/message/serialization.rb:80:in `set_field_bytes'
  2017-06-22 15:50:00 -0400 [error]: /usr/lib/ruby/gems/2.3.0/gems/protobuf-3.7.5/lib/protobuf/message/serialization.rb:42:in `block in decode_from'
  2017-06-22 15:50:00 -0400 [error]: /usr/lib/ruby/gems/2.3.0/gems/protobuf-3.7.5/lib/protobuf/decoder.rb:24:in `decode_each_field'
  2017-06-22 15:50:00 -0400 [error]: /usr/lib/ruby/gems/2.3.0/gems/protobuf-3.7.5/lib/protobuf/message/serialization.rb:41:in `decode_from'
  2017-06-22 15:50:00 -0400 [error]: /usr/lib/ruby/gems/2.3.0/gems/protobuf-3.7.5/lib/protobuf/message/serialization.rb:35:in `decode'
  2017-06-22 15:50:00 -0400 [error]: /usr/lib/ruby/gems/2.3.0/gems/protobuf-3.7.5/lib/protobuf/message/serialization.rb:11:in `decode'
  2017-06-22 15:50:00 -0400 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-juniper-telemetry-0.3.0/lib/fluent/plugin/parser_juniper_jti.rb:34:in `parse'
  2017-06-22 15:50:00 -0400 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.29/lib/fluent/plugin/socket_util.rb:142:in `on_message'
  2017-06-22 15:50:00 -0400 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.29/lib/fluent/plugin/socket_util.rb:46:in `call'
  2017-06-22 15:50:00 -0400 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.29/lib/fluent/plugin/socket_util.rb:46:in `on_readable'
  2017-06-22 15:50:00 -0400 [error]: /usr/lib/ruby/gems/2.3.0/gems/cool.io-1.4.5/lib/cool.io/io.rb:186:in `on_readable'
  2017-06-22 15:50:00 -0400 [error]: /usr/lib/ruby/gems/2.3.0/gems/cool.io-1.4.5/lib/cool.io/loop.rb:88:in `run_once'
  2017-06-22 15:50:00 -0400 [error]: /usr/lib/ruby/gems/2.3.0/gems/cool.io-1.4.5/lib/cool.io/loop.rb:88:in `run'
  2017-06-22 15:50:00 -0400 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.29/lib/fluent/plugin/socket_util.rb:133:in `run'
2017-06-22 15:50:00 -0400 fluent.error: {"error":"#<Protobuf::InvalidWireType: 4>","error_class":"Protobuf::InvalidWireType","host":"10.150.0.5","message":"\"0\\x00\\x00\\x00\\x01\\x00\\x00\\x00\\b\\xD1\\xB8\\xEB\\xD1\\x9C\\xD2\\xD4\\x02\\x1A%\\n\\x1Cprtgc-qfx5100-vc-1:xe-0/0/16\\\"\\x05\\x12\\x03\\x10\\xC0\\x06\" error=#<Protobuf::InvalidWireType: 4> error_class=Protobuf::InvalidWireType host=\"10.150.0.5\""}
2017-06-22 15:50:00 -0400 fluent.error: {"error":"#<TypeError: Expected value of type 'Protobuf::Field::Uint64Field' for field timestamp, but got 'String'>","error_class":"TypeError","host":"10.150.0.5","message":"\"2\\x00\\x00\\x00\\x01\\x00\\x00\\x00\\b\\x8C\\xA9\\xEC\\xD1\\x9C\\xD2\\xD4\\x02\\x1A'\\n\\x1Eprtgc-qfx5100-vc-1:xe-1/0/50:0\\\"\\x05\\x12\\x03\\x10\\xE00\" error=#<TypeError: Expected value of type 'Protobuf::Field::Uint64Field' for field timestamp, but got 'String'> error_class=TypeError host=\"10.150.0.5\""}
2017-06-22 15:50:01 -0400 [error]: "W\x00\x00\x00\x01\x00\x00\x00\b\xC1\xE8\xA8\xD2\x9C\xD2\xD4\x02\x1A%\n\x1Cprtgc-qfx5100-vc-1:xe-0/0/13\"\x05\x12\x03\x10\x90\b\x1A%\n\x1Cprtgc-qfx5100-vc-1:xe-0/0/16\"\x05\x12\x03\x10\x80" error=#<Protobuf::InvalidWireType: 7> error_class=Protobuf::InvalidWireType host="10.150.0.5"
  2017-06-22 15:50:01 -0400 [error]: /usr/lib/ruby/gems/2.3.0/gems/protobuf-3.7.5/lib/protobuf/decoder.rb:21:in `decode_each_field'
  2017-06-22 15:50:01 -0400 [error]: /usr/lib/ruby/gems/2.3.0/gems/protobuf-3.7.5/lib/protobuf/message/serialization.rb:41:in `decode_from'
  2017-06-22 15:50:01 -0400 [error]: /usr/lib/ruby/gems/2.3.0/gems/protobuf-3.7.5/lib/protobuf/message/serialization.rb:35:in `decode'
  2017-06-22 15:50:01 -0400 [error]: /usr/lib/ruby/gems/2.3.0/gems/protobuf-3.7.5/lib/protobuf/message/serialization.rb:11:in `decode'
  2017-06-22 15:50:01 -0400 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-juniper-telemetry-0.3.0/lib/fluent/plugin/parser_juniper_jti.rb:34:in `parse'
  2017-06-22 15:50:01 -0400 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.29/lib/fluent/plugin/socket_util.rb:142:in `on_message'
  2017-06-22 15:50:01 -0400 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.29/lib/fluent/plugin/socket_util.rb:46:in `call'
  2017-06-22 15:50:01 -0400 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.29/lib/fluent/plugin/socket_util.rb:46:in `on_readable'
  2017-06-22 15:50:01 -0400 [error]: /usr/lib/ruby/gems/2.3.0/gems/cool.io-1.4.5/lib/cool.io/io.rb:186:in `on_readable'
  2017-06-22 15:50:01 -0400 [error]: /usr/lib/ruby/gems/2.3.0/gems/cool.io-1.4.5/lib/cool.io/loop.rb:88:in `run_once'
  2017-06-22 15:50:01 -0400 [error]: /usr/lib/ruby/gems/2.3.0/gems/cool.io-1.4.5/lib/cool.io/loop.rb:88:in `run'
  2017-06-22 15:50:01 -0400 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.29/lib/fluent/plugin/socket_util.rb:133:in `run'
2017-06-22 15:50:01 -0400 fluent.error: {"error":"#<Protobuf::InvalidWireType: 7>","error_class":"Protobuf::InvalidWireType","host":"10.150.0.5","message":"\"W\\x00\\x00\\x00\\x01\\x00\\x00\\x00\\b\\xC1\\xE8\\xA8\\xD2\\x9C\\xD2\\xD4\\x02\\x1A%\\n\\x1Cprtgc-qfx5100-vc-1:xe-0/0/13\\\"\\x05\\x12\\x03\\x10\\x90\\b\\x1A%\\n\\x1Cprtgc-qfx5100-vc-1:xe-0/0/16\\\"\\x05\\x12\\x03\\x10\\x80\" error=#<Protobuf::InvalidWireType: 7> error_class=Protobuf::InvalidWireType host=\"10.150.0.5\""}

**Comment by 3fr61n** [comment]
Hi

It seems you're using a QFX, could you please try to change the port to 50020, test it again?

From  http://open-nti.readthedocs.io/en/latest/datastreaming.html

```
Currently the collector accept:
Analyticsd (QFX5k) streams in JSON/UDP on port UDP/50020
Juniper Telemetry Interface (MX/PTX) streams in GPB/UDP on port UDP/50000
```
Regards

**Comment by pr-acassera** [comment]
That was it thank you, sorry about the confusion.  I also needed to change the format to JSON from gpb.  Getting data now.
