### ISSUE TITLE
Make Start Throwing Error - Install Problem, Invalid port 8125

### ISSUE THREAD

**Issue by mnanduri** [Juniper/open-nti#174]
Getting below error when I tried to make start. Any help would be really appreciated.

root@Jumphost2:/home/open-nti# make start
Use docker compose file: docker-compose.yml
IMAGE_TAG=latest docker-compose -f docker-compose.yml up -d

ERROR: for opennti  Invalid port "_ServicePort(target=8125, published=8125, protocol=u'udp', mode=None, external_ip=None)", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 68, in main
    command()
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 118, in perform_command
    handler(command, command_options)
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 926, in up
    scale_override=parse_scale_args(options['--scale']),
  File "/usr/local/lib/python2.7/dist-packages/compose/project.py", line 424, in up
    get_deps
  File "/usr/local/lib/python2.7/dist-packages/compose/parallel.py", line 69, in parallel_execute
    raise error_to_reraise
ValueError: Invalid port "_ServicePort(target=8125, published=8125, protocol=u'udp', mode=None, external_ip=None)", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
make: *** [start] Error 1

**Comment by mnanduri** [comment]
Tried again by removing images, getting same error 

Step 13/13 : CMD /source/start-input-snmp.sh
 ---> Running in 81767ced3075
 ---> 48adb857550d
Removing intermediate container 81767ced3075
Successfully built 48adb857550d
Successfully tagged opennti_input-snmp:latest
WARNING: Image for service input-snmp was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.

ERROR: for opennti  Invalid port "_ServicePort(target=8125, published=8125, protocol=u'udp', mode=None, external_ip=None)", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 68, in main
    command()
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 118, in perform_command
    handler(command, command_options)
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 926, in up
    scale_override=parse_scale_args(options['--scale']),
  File "/usr/local/lib/python2.7/dist-packages/compose/project.py", line 424, in up
    get_deps
  File "/usr/local/lib/python2.7/dist-packages/compose/parallel.py", line 69, in parallel_execute
    raise error_to_reraise
ValueError: Invalid port "_ServicePort(target=8125, published=8125, protocol=u'udp', mode=None, external_ip=None)", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
make: *** [start] Error 1

**Comment by 3fr61n** [comment]
Hi,

Did you still have this problem? if so try to remove the input-snmp stanza from docker-compose file and try again (just to confirm if this problem belong only to that plugin installation)

Regarfds

**Comment by mnanduri** [comment]
Thanks for getting back. I forgot to close this, issue got resolved once i
rebooted the server and started the docker.

Cheers,
-Mohan
