### ISSUE TITLE
Netconf throws ConnectError

### ISSUE THREAD

**Issue by mpergament** [Juniper/open-nti#43]
Workaround until we commit a change:
Inside container downgrade cryptography module to 1.2.1 (pip install cryptography==1.2.1)

Once downgraded you should not see errors below.

2016-05-19 06:07:07 root ERROR Thread-2  :  ConnectError(host: 138.187.21.15, msg: 'EntryPoint' object has no attribute 'resolve')
Traceback (most recent call last):
  File "/opt/open-nti/open-nti.py", line 515, in collector
    jdev.open()
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/device.py", line 483, in open
    raise cnx_err
ConnectError: ConnectError(host: 138.187.21.15, msg: 'EntryPoint' object has no attribute 'resolve')
2016-05-19 06:07:07 _open-nti_ ERROR Thread-2  :  [138.187.21.15]: Skipping host due connectivity issue
2016-05-19 06:07:07 root ERROR Thread-1  :  ConnectError(host: 138.187.21.16, msg: 'EntryPoint' object has no attribute 'resolve')
Traceback (most recent call last):
  File "/opt/open-nti/open-nti.py", line 515, in collector
    jdev.open()
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/device.py", line 483, in open
    raise cnx_err
ConnectError: ConnectError(host: 138.187.21.16, msg: 'EntryPoint' object has no attribute 'resolve')
2016-05-19 06:07:07 _open-nti_ ERROR Thread-1  :  [138.187.21.16]: Skipping host due connectivity issue
2016-05-19 06:07:09 ncclient.transport.ssh ERROR Thread-47 :  Unknown exception: 'EntryPoint' object has no attribute 'resolve'
2016-05-19 06:07:09 ncclient.transport.ssh ERROR Thread-47 :  Traceback (most recent call last):
2016-05-19 06:07:09 ncclient.transport.ssh ERROR Thread-47 :    File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 1757, in run
2016-05-19 06:07:09 ncclient.transport.ssh ERROR Thread-47 :      self.kex_engine.parse_next(ptype, m)
2016-05-19 06:07:09 ncclient.transport.ssh ERROR Thread-47 :    File "/usr/local/lib/python2.7/dist-packages/paramiko/kex_group1.py", line 75, in parse_next
2016-05-19 06:07:09 ncclient.transport.ssh ERROR Thread-47 :      return self._parse_kexdh_reply(m)
2016-05-19 06:07:09 ncclient.transport.ssh ERROR Thread-47 :    File "/usr/local/lib/python2.7/dist-packages/paramiko/kex_group1.py", line 111, in _parse_kexdh_reply
2016-05-19 06:07:09 ncclient.transport.ssh ERROR Thread-47 :      self.transport._verify_key(host_key, sig)
2016-05-19 06:07:09 ncclient.transport.ssh ERROR Thread-47 :    File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 1602, in _verify_key
2016-05-19 06:07:09 ncclient.transport.ssh ERROR Thread-47 :      key = self._key_info[self.host_key_type](Message(host_key))
2016-05-19 06:07:09 ncclient.transport.ssh ERROR Thread-47 :    File "/usr/local/lib/python2.7/dist-packages/paramiko/rsakey.py", line 58, in __init__
2016-05-19 06:07:09 ncclient.transport.ssh ERROR Thread-47 :      ).public_key(default_backend())
2016-05-19 06:07:09 ncclient.transport.ssh ERROR Thread-47 :    File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/__init__.py", line 35, in default_backend
2016-05-19 06:07:09 ncclient.transport.ssh ERROR Thread-47 :      _default_backend = MultiBackend(_available_backends())
2016-05-19 06:07:09 ncclient.transport.ssh ERROR Thread-47 :    File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/__init__.py", line 22, in _available_backends
2016-05-19 06:07:09 ncclient.transport.ssh ERROR Thread-47 :      "cryptography.backends"
2016-05-19 06:07:09 ncclient.transport.ssh ERROR Thread-47 :  AttributeError: 'EntryPoint' object has no attribute 'resolve'
2016-05-19 06:07:09 ncclient.transport.ssh ERROR Thread-47 :
2016-05-19 06:07:09 root ERROR Thread-3  :  ConnectError(host: 138.187.93.37, msg: 'EntryPoint' object has no attribute 'resolve')
Traceback (most recent call last):
  File "/opt/open-nti/open-nti.py", line 515, in collector
    jdev.open()
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/device.py", line 483, in open
    raise cnx_err
ConnectError: ConnectError(host: 138.187.93.37, msg: 'EntryPoint' object has no attribute 'resolve')

**Comment by dgarros** [comment]
I fix it, 
please check if you can

**Comment by dgarros** [comment]
fixed
