### ISSUE TITLE
OpenNTI - FluentD parser issue in Data Streaming Collector

### ISSUE THREAD

**Issue by jsanz01** [Juniper/open-nti#88]
Hello all,
we are just installing and configuring OpenNTI to monitor some QFX5100 switches. They are configured as a virtual chassis and are running JUNOS 14.1X53-D35.3 built 2016-02-29 23:35:46 UTC.
We have installed OpenNTI virtualized in monitoring server.

**OpenNTI DataCollectionAgent** is working properly and we are seeing information in Grafana.
However, when talking about **OpenNTI DataStreamingCollector**, it is not working.
Docker Proxy is exposing 172.17.0.1 IP Address and opennti_input_jti container is located at 172.17.0.4 IP Address.
Our Switches are sending the UDP streaming data to the 50020 port. 
Then a parser error is registered in the dockers logs (see details below):
_<JSON::ParserError: 757: unexpected token at '�\u0003'_

Could you let us know what can we do to solve this topic?

Thank in advance, Jose

016-10-19T15:18:27.361858000Z   2016-10-19 17:18:27 +0200 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.26/lib/fluent/plugin/socket_util.rb:46:in `call'
2016-10-19T15:18:27.362022000Z   2016-10-19 17:18:27 +0200 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.26/lib/fluent/plugin/socket_util.rb:46:in`on_readable'
2016-10-19T15:18:27.362189000Z   2016-10-19 17:18:27 +0200 [error]: /usr/lib/ruby/gems/2.3.0/gems/cool.io-1.4.4/lib/cool.io/io.rb:186:in `on_readable'
2016-10-19T15:18:27.362376000Z   2016-10-19 17:18:27 +0200 [error]: /usr/lib/ruby/gems/2.3.0/gems/cool.io-1.4.4/lib/cool.io/loop.rb:88:in`run_once'
2016-10-19T15:18:27.362566000Z   2016-10-19 17:18:27 +0200 [error]: /usr/lib/ruby/gems/2.3.0/gems/cool.io-1.4.4/lib/cool.io/loop.rb:88:in `run'
2016-10-19T15:18:27.362739000Z   2016-10-19 17:18:27 +0200 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.26/lib/fluent/plugin/socket_util.rb:133:in`run'
2016-10-19T15:18:27.400248000Z 2016-10-19 17:18:27 +0200 fluent.error: {"error":"#<JSON::ParserError: 757: unexpected token at '9\u0005'>","error_class":"JSON::ParserError","host":"172.17.0.1","message":"\"9\x05\x00\x00\x01\x00\x00\x00\b\xE1\x9B\xD1\xE9\x8B\xE7\xCF\x02\x1AD\n\x11MXMETSW1:xe-2/0/0\\"/\n-\x10\xD0\x9B\xD3\x03\x18\xFC\x9A\xD3\x03(T8\xFD\xDC\xA6\x9F\x17@\x0FX\x81\x9D\xCD\x03`\\xEC\\xE4\\xAF\\x03h\\x95\\xFC\\x1Ap\\x80\\xBC\\x02\\x80\\x01\\x88\\x91\\xC4\\xAE\\x1A\\x1AD\\n\\x11MXMETSW1:xe-2/0/2\\\"/\\n-\\x10\\x9E\\xCD7\\x18\\xAB\\xCC7 <(78\\xD7\\x9B\\x9B\\x83\\x04@.X\\xEC\\xDAZ`\x99\xA3=h\xC2\xFB\x1Ap\x91\xBC\x02\x80\x01\xA0\xB0\x8B[\x88\x01.\x1AJ\n\x11MXMETSW1:xe-2/0/3\\"5\n3\x10\xF8\x8A\x9A\x04\x18\xD1\x84\x9A\x04\xC6\x01(\xE1\x048\xC1\xA4\x96\xAF\x05X\xFC\x96\xB7\b`\\x8A\\xEA\\x99\\bh\\x99\\xF5\\x1Ap\\xD9\\xB7\\x02\\x80\\x01\\xFC\\xC9\\xF5\\xF4T\\x88\\x01\\xB7\\b\\x1AG\\n\\x11MXMETSW1:xe-2/0/5\\\"2\\n0\\x10\\xBE\\x8C\\x11\\xBE\\x8C\\x118\\xF8\\xA2\\xC6\\bX\\x96\\xA3\\xCF\\xEE@`#h\xDE\x9D\xCF\xEE@p\x95\x05x\xF7/\x80\x01\xCA\xE3\xBA\x82\x97\xB2\x05\x88\x01\x8E\x85\xFE\x03\x1AR\n\x12MXMETSW1:xe-2/0/20\\"<\n:\x10\xB4\xE3\x8F\x16\x18\x9F\xF0\x8B\x16(\x95\xF3\x030\b8\xCE\xEF\xD5\xDBK@\xE8\aX\x99\xF4\xB0g`\\xAB\\xA2\\xA1gh\\xE9\\xF2\\x06p\\x85\\xDF\\bxi\\x80\\x01\\xBE\\xBD\\xDB\\xCE\\x87\\x01\\x88\\x01\\xB3\\x92\\x01\\x1AJ\\n\\x12MXMETSW1:xe-2/0/21\\\"4\\n2\\x10\\xEF\\x87\\xB5\\x16\\x18\\xC7\\xD3\\xB3\\x16 )(\\xFF\\xB3\\x018\\x9C\\x9A\\xEA\\xD10X\\xCA\\xBB\\xD7\\x02`\xF4\xAA\xC5\x02h\xD3\xF2\x06p\x83\x9E\v\x80\x01\xBE\xF6\xE5\xD2\x05\x88\x01W\x1AR\n\x12MXMETSW1:xe-2/0/22\\"<\n:\x10\x97\xA8\xF2\x13\x18\xA6\xF4\xF0\x13\x15(\xDC\xB3\x01088\xF8\xCC\xD5\xDD-@\x8E}X\xDF\xEC\xB9\x02`\\xBD\\xDB\\xA7\\x02h\\xF4\\xF2\\x06p\\xAE\\x9E\\vx\\x02\\x80\\x01\\x91\\x82\\xD5\\xB2\\x03\\x88\\x01\\xBF\\x01\\x1AQ\\n\\x12MXMETSW1:xe-2/0/28\\\";\\n9\\x10\\xED\\xB3\\x81\\b\\x18\\xB0\\xDF\\xBB\\x06\\xBA\\xD4\\xC5\\x01(\\x030\\x018\\xCE\\xE5\\xDC\\xCB+@\\xBC\\x01X\\xEC\\xDD\\xB0\\a`\xC4\x9E\xEC\x05h\xFD\xAA\xC4\x01p\xAB\x14\x80\x01\xF2\xD0\xE9\xF6-\x88\x01\xAF\x01\x1AX\n\x12MXMETSW1:xe-2/0/30\\"B\n@\x10\x99\xD7\xB9\xDA\x01\x18\xC5\xC8\xB9\xDA\x01(\xD4\x0E0\x8B\x018\xCE\xED\xAC\x86\xC0\x03@\xF3\x9E\x02X\xA7\xD0\xE0\xB5\x02`\\xC0\\xE6\\xD8\\xB5\\x02h\\xE5\\xF3\\x06p\\x82vx\\xC6\\x01\\x80\\x01\\xF7\\x97\\xE6\\xD9\\xF0\\x04\\x88\\x01\\x8D\\x93\\x03\\x1AQ\\n\\x12MXMETSW1:xe-2/0/31\\\";\\n9\\x10\\xC3\\xA2\\x9E.\\x18\\xA3\\x9F\\x9E. +(\\xF5\\x020\\x1D8\\xB5\\xE1\\xAB\\xBCi@\\xD4FX\\x89\\xA3\\xD7\\e`\xDF\xAD\xCF\eh\xCB\xF3\x06p\xDF\x81\x01x\x12\x80\x01\xAA\x87\x82\xF1E\x88\x01\xD0/\x1AQ\n\x12MXMETSW1:xe-2/0/32\\";\n9\x10\xFD\xE8\xC3-\x18\x8B\xE6\xC3-\x14(\xDE\x020\x1D8\xE6\xB2\x8B\x9Bh@\x87EX\x88\xF2\xA7\e`\\xB7\\xFC\\x9F\\eh\\xE8\\xF3\\x06p\\xE9\\x81\\x01x\\x11\\x80\\x01\\xC8\\xD8\\xB0\\xE1D\\x88\\x01\\xF8.\\x1AQ\\n\\x12MXMETSW1:xe-2/0/33\\\";\\n9\\x10\\xA9\\x98\\xD2-\\x18\\xB2\\x95\\xD2-\\x17(\\xE0\\x020\\x1E8\\xEC\\xB8\\xA8\\xDAh@\\xC8FX\\x83\\x9C\\xB6\\e`\xBE\xA6\xAE\eh\xD9\xF3\x06p\xEC\x81\x01x\x12\x80\x01\xAF\xFE\xFA\xFAD\x88\x01\xB7/\x1AQ\n\x12MXMETSW1:xe-2/0/34\\";\n9\x10\x81\xBD\xF2-\x18\xD0\xB9\xF2- >(\xF3\x020\x1D8\x91\xD3\xF6\xB3h@\x94CX\xF9\xD0\xB9\e`\\xEC\\xDB\\xB1\\eh\\xC7\\xF3\\x06p\\xC6\\x81\\x01x\\x11\\x80\\x01\\xA5\\xB2\\xD9\\x80E\\x88\\x01\\x87.\\x1AQ\\n\\x12MXMETSW1:xe-2/0/35\\\";\\n9\\x10\\xE3\\xD5\\xF5-\\x18\\xD0\\xD2\\xF5- ,(\\xE7\\x020\\x1D8\\xBB\\xAA\\x96\\xE2h@\\xD8DX\\x93\\xB7\\xBE\\e`\xF9\xC1\xB6\eh\xC2\xF3\x06p\xD8\x81\x01x\x11\x80\x01\xCD\xB7\xFC\x98E\x88\x01\xF4-\x1AD\n\x12MXMETSW1:xe-2/0/38\\".\n,\x10\xA9\xE9\a\x18\xC6u\x85\x97\x03(\xDE\xDC\x038\xDE\xFC\x8F\aX\xC6\xBBo`\\xCA\\ah\\xCD\\x92np\\xAF\\xA1\\x01\\x80\\x01\\xDF\\xF3\\x96H\\x88\\x01\\x1F\\x1AN\\n\\x12MXMETSW1:xe-2/0/46\\\"8\\n6\\x10\\xC2\\xAC\\xE7\\x01\\x18\\xA9\\xAC\\xE7\\x01(\\x190\\x028\\xCC\\xF1\\x98\\x82\\x02@\\xC0\\x02X\\x98\\xD7\\xB4\\x02`\xBA\xB9\xF1\x01h\xD3\xD9\x1Cp\x8B\xC4&x\x02\x80\x01\xD3\xDA\x82\xE6\x01\x88\x01\xF8\x01\x1A7\n\x12MXMETSW1:xe-2/0/47\\"!\n\x1F\x10\x01\x18\x018@X\xEB\xFFG`\\xE8\\xE1\\x04h\\xDF\\xD9\\x1Cp\\xA4\\xC4&\\x80\\x01\\xA3\\xD9\\xE38\\x88\\x01\\x17\" error=#<JSON::ParserError: 757: unexpected token at '9\u0005'> error_class=JSON::ParserError host=\"172.17.0.1\""}
2016-10-19T15:18:27.673318000Z 2016-10-19 17:18:27 +0200 [error]: "\xAA\x03\x00\x00\x01\x00\x00\x00\b\xE0\xF2\xED\xE9\x8B\xE7\xCF\x02\x1AG\n\x11MXMETSW1:xe-1/0/0\"2\n0\x10\xC6\x02 \xBC\x02(\n8\xE6\xB0\x01X\xE6\xD6\x94\xDE;`\xBC\x01h\xA8\xD0\x94\xDE;p\x82\x05x\xF7/\x80\x01\xEE\xE6\xC7\xC0\xCC\xFB\x04\x88\x01\x8E\x82\xFE\x03\x1AG\n\x11MXMETSW1:xe-1/0/1\"2\n0\x10\xFE\x01 \xF7\x01(\a8\xFC\x86\x01X\xAD\x92\x9E\xDE;`\xBC\x01h\xEC\x8B\x9E\xDE;p\x85\x05x\xF6/\x80\x01\xBC\xEA\xA2\xA5\xCD\xFB\x04\x88\x01\xEC\xFE\xFD\x03\x1AG\n\x11MXMETSW1:xe-1/0/2\"2\n0\x10\xA0\x02 \x99\x02(\a8\xF2\x97\x01X\xA6\xB9\x9E\xDE;`\xBC\x01h\xE4\xB2\x9E\xDE;p\x86\x05x\xF7/\x80\x01\xAE\x94\xC0\xA8\xCD\xFB\x04\x88\x01\xB1\x85\xFE\x03\x1AG\n\x11MXMETSW1:xe-1/0/3\"2\n0\x10\x9C\x02 \x87\x02(\x158\xBC\xC1\x01X\xBB\xB9\xFA\xDD;`\xBC\x01h\x88\xB3\xFA\xDD;p\xF7\x04x\xF7/\x80\x01\xEE\xC3\xBF\xA9\xCA\xFB\x04\x88\x01\x8E\x82\xFE\x03\x1AG\n\x11MXMETSW1:xe-1/0/4\"2\n0\x10\x88\x1E \xE5\x19(\xA3\x048\x94\x80\x10X\xA1\xF7\x90\xDE;`\xBC\x01h\xFB\xF4\x90\xDE;pjx\xF5/\x80\x01\xFA\xC9\xAF\x99\xCC\xFB\x04\x88\x01\xCC\xF4\xFD\x03\x1AH\n\x12MXMETSW1:xe-1/0/18\"2\n0\x10\xB3\x91\x01\x18\x86\x91\x01 #(\n8\xAD\xAF\xE8\tX\xE7\xE9\xD7\x03`\x8F\xA9\x02h\xB0\xD8\x1Cp\xA8\xE8\xB8\x03x\x02\x80\x01\xA2\xE5\xD8\x80\x02\x88\x01\xBA\x01\x1AI\n\x12MXMETSW1:xe-1/0/19\"3\n1\x10\xAE\x83\x15\x18\x94\x83\x15 \x13(\a8\xC8\x86\xDC\xF5\x01X\xED\xF5\xD8\x03`\xDA\xB3\x03h\xC3\xD8\x1Cp\xD0\xE9\xB8\x03x\x02\x80\x01\x89\x99\xA5\x81\x02\x88\x01\xA7\x02\x1AE\n\x12MXMETSW1:xe-1/0/20\"/\n-\x10\x94\x02\x18\xF9\x01 \x14(\a8\xC8\x91\x01X\xAB\xA3\xD7\x03`\xD5\xE0\x01h\xBD\xD8\x1Cp\x99\xEA\xB8\x03x\x02\x80\x01\x94\xF9\xA8\x80\x02\x88\x01\xBA\x01\x1AE\n\x12MXMETSW1:xe-1/0/21\"/\n-\x10\x86\x02\x18\xC5\x01 4(\r8\x88\x98\x01X\xB8\xA1\xD7\x03`\xCA\xE1\x01h\x96\xD8\x1Cp\xD8\xE7\xB8\x03x\x02\x80\x01\x97\xEF\xA7\x80\x02\x88\x01\xBA\x01\x1AE\n\x12MXMETSW1:xe-1/0/22\"/\n-\x10\xB0\x11\x18\x85\x11 !(\n8\xE0\xE2\x0FX\xDE\xB3\xD7\x03`\xC9\xF3\x01h\xB0\xD8\x1Cp\xE5\xE7\xB8\x03x\x02\x80\x01\xC3\xE4\xB4\x80\x02\x88\x01\xBA\x01\x1AD\n\x12MXMETSW1:xe-1/0/40\".\n,\x10\xCE\xD1\xCD\e\x18\xA3\xD1\xCD\e \"(\t8\xCD\xE4\x83\xB4\x11X\x86\xFD\xB8\e`\xB1\xE1\xB1\eh\xF4\xF1\x06p\xE1)\x80\x01\xB0\x98\xAE\xFE\x10\x1A/\n\x12MXMETSW1:xe-1/0/55\"\x19\n\x17X\xEE\xDE\xC4\x01h\xD3\xDA\xC4\x01p\x9B\x04\x80\x01\xEA\xBF\xFE\xD0\x01\x88\x01u\x1AQ\n\x12MXMETSW1:xe-1/0/56\";\n9\x10\xFA\xEB\xAF\t\x18\xD9\xC1\x81\t \x8C\xAA.(\x150\x068\x81\xA5\x94\xA1\t@\x8E\x06X\x8D\xDF\xDF\x0E`\x8F\xC4\xA5\x0Eh\xCF\x90:p\xAF\nx\x15\x80\x01\xAB\xA4\xE4\x91/\x88\x01\xF7\x16" error=#<JSON::ParserError: 757: unexpected token at '�'> error_class=JSON::ParserError host="172.17.0.1"
2016-10-19T15:18:27.674054000Z   2016-10-19 17:18:27 +0200 [error]: suppressed same stacktrace
2016-10-19T15:18:27.700570000Z 2016-10-19 17:18:27 +0200 fluent.error: {"error":"#<JSON::ParserError: 757: unexpected token at '�\u0003'>","error_class":"JSON::ParserError","host":"172.17.0.1","message":"\"\\xAA\\x03\\x00\\x00\\x01\\x00\\x00\\x00\\b\\xE0\\xF2\\xED\\xE9\\x8B\\xE7\\xCF\\x02\\x1AG\\n\\x11MXMETSW1:xe-1/0/0\\\"2\\n0\\x10\\xC6\\x02\\xBC\\x02(\\n8\\xE6\\xB0\\x01X\\xE6\\xD6\\x94\\xDE;`\xBC\x01h\xA8\xD0\x94\xDE;p\x82\x05x\xF7/\x80\x01\xEE\xE6\xC7\xC0\xCC\xFB\x04\x88\x01\x8E\x82\xFE\x03\x1AG\n\x11MXMETSW1:xe-1/0/1\\"2\n0\x10\xFE\x01\xF7\x01(\a8\xFC\x86\x01X\xAD\x92\x9E\xDE;`\\xBC\\x01h\\xEC\\x8B\\x9E\\xDE;p\\x85\\x05x\\xF6/\\x80\\x01\\xBC\\xEA\\xA2\\xA5\\xCD\\xFB\\x04\\x88\\x01\\xEC\\xFE\\xFD\\x03\\x1AG\\n\\x11MXMETSW1:xe-1/0/2\\\"2\\n0\\x10\\xA0\\x02\\x99\\x02(\\a8\\xF2\\x97\\x01X\\xA6\\xB9\\x9E\\xDE;`\xBC\x01h\xE4\xB2\x9E\xDE;p\x86\x05x\xF7/\x80\x01\xAE\x94\xC0\xA8\xCD\xFB\x04\x88\x01\xB1\x85\xFE\x03\x1AG\n\x11MXMETSW1:xe-1/0/3\\"2\n0\x10\x9C\x02\x87\x02(\x158\xBC\xC1\x01X\xBB\xB9\xFA\xDD;`\\xBC\\x01h\\x88\\xB3\\xFA\\xDD;p\\xF7\\x04x\\xF7/\\x80\\x01\\xEE\\xC3\\xBF\\xA9\\xCA\\xFB\\x04\\x88\\x01\\x8E\\x82\\xFE\\x03\\x1AG\\n\\x11MXMETSW1:xe-1/0/4\\\"2\\n0\\x10\\x88\\x1E\\xE5\\x19(\\xA3\\x048\\x94\\x80\\x10X\\xA1\\xF7\\x90\\xDE;`\xBC\x01h\xFB\xF4\x90\xDE;pjx\xF5/\x80\x01\xFA\xC9\xAF\x99\xCC\xFB\x04\x88\x01\xCC\xF4\xFD\x03\x1AH\n\x12MXMETSW1:xe-1/0/18\\"2\n0\x10\xB3\x91\x01\x18\x86\x91\x01 #(\n8\xAD\xAF\xE8\tX\xE7\xE9\xD7\x03`\\x8F\\xA9\\x02h\\xB0\\xD8\\x1Cp\\xA8\\xE8\\xB8\\x03x\\x02\\x80\\x01\\xA2\\xE5\\xD8\\x80\\x02\\x88\\x01\\xBA\\x01\\x1AI\\n\\x12MXMETSW1:xe-1/0/19\\\"3\\n1\\x10\\xAE\\x83\\x15\\x18\\x94\\x83\\x15\\x13(\\a8\\xC8\\x86\\xDC\\xF5\\x01X\\xED\\xF5\\xD8\\x03`\xDA\xB3\x03h\xC3\xD8\x1Cp\xD0\xE9\xB8\x03x\x02\x80\x01\x89\x99\xA5\x81\x02\x88\x01\xA7\x02\x1AE\n\x12MXMETSW1:xe-1/0/20\\"/\n-\x10\x94\x02\x18\xF9\x01\x14(\a8\xC8\x91\x01X\xAB\xA3\xD7\x03`\\xD5\\xE0\\x01h\\xBD\\xD8\\x1Cp\\x99\\xEA\\xB8\\x03x\\x02\\x80\\x01\\x94\\xF9\\xA8\\x80\\x02\\x88\\x01\\xBA\\x01\\x1AE\\n\\x12MXMETSW1:xe-1/0/21\\\"/\\n-\\x10\\x86\\x02\\x18\\xC5\\x014(\\r8\\x88\\x98\\x01X\\xB8\\xA1\\xD7\\x03`\xCA\xE1\x01h\x96\xD8\x1Cp\xD8\xE7\xB8\x03x\x02\x80\x01\x97\xEF\xA7\x80\x02\x88\x01\xBA\x01\x1AE\n\x12MXMETSW1:xe-1/0/22\\"/\n-\x10\xB0\x11\x18\x85\x11 !(\n8\xE0\xE2\x0FX\xDE\xB3\xD7\x03`\\xC9\\xF3\\x01h\\xB0\\xD8\\x1Cp\\xE5\\xE7\\xB8\\x03x\\x02\\x80\\x01\\xC3\\xE4\\xB4\\x80\\x02\\x88\\x01\\xBA\\x01\\x1AD\\n\\x12MXMETSW1:xe-1/0/40\\\".\\n,\\x10\\xCE\\xD1\\xCD\\e\\x18\\xA3\\xD1\\xCD\\e \\\"(\\t8\\xCD\\xE4\\x83\\xB4\\x11X\\x86\\xFD\\xB8\\e`\xB1\xE1\xB1\eh\xF4\xF1\x06p\xE1)\x80\x01\xB0\x98\xAE\xFE\x10\x1A/\n\x12MXMETSW1:xe-1/0/55\\"\x19\n\x17X\xEE\xDE\xC4\x01h\xD3\xDA\xC4\x01p\x9B\x04\x80\x01\xEA\xBF\xFE\xD0\x01\x88\x01u\x1AQ\n\x12MXMETSW1:xe-1/0/56\\";\n9\x10\xFA\xEB\xAF\t\x18\xD9\xC1\x81\t \x8C\xAA.(\x150\x068\x81\xA5\x94\xA1\t@\x8E\x06X\x8D\xDF\xDF\x0E`\x8F\xC4\xA5\x0Eh\xCF\x90:p\xAF\nx\x15\x80\x01\xAB\xA4\xE4\x91/\x88\x01\xF7\x16\" error=#<JSON::ParserError: 757: unexpected token at '�\u0003'> error_class=JSON::ParserError host=\"172.17.0.1\""}

**Comment by dgarros** [comment]
Hi

Please could you capture some packets coming from QFX5100 on the collector and also provide the configuration (related to analytics) for this device

Thanks
Damien

**Comment by jsanz01** [comment]
Of course Damien,
here you have a wireshark dump.

This form is not allowing me to upload a ZIP file. So, I have used a temporary repository. This is the resulting URL to download the dump:

[http://expirebox.com/download/d9b3a37f5eb2a46a8cd7f3c896b26548.html](url)

Switch is sending the information from source IP: 10.0.0.1

Best regards, Jose

**Comment by dgarros** [comment]
Hi Jose

I would bet that you have configure the device to stream data in GPB and not JSON.
the collector do not support GPB for QFX5100 today, only JSON
It does support GPB for MX though

Damien

**Comment by jsanz01** [comment]
Hi Damien,
you were right. It was the root cause of the issue. We have changed to JSON and now Grafana is receiving data.
We are now evaluating the full OpenNTI result.
Thanks for your support!
Best regards, Jose

**Comment by dgarros** [comment]
Great, let us know if you have more questions or feedback
